package sakila;

// Generated 07-mar-2017 10:05:25 by Hibernate Tools 3.4.0.CR1

/**
 * NicerButSlowerFilmList generated by hbm2java
 */
public class NicerButSlowerFilmList implements java.io.Serializable {

	private NicerButSlowerFilmListId id;

	public NicerButSlowerFilmList() {
	}

	public NicerButSlowerFilmList(NicerButSlowerFilmListId id) {
		this.id = id;
	}

	public NicerButSlowerFilmListId getId() {
		return this.id;
	}

	public void setId(NicerButSlowerFilmListId id) {
		this.id = id;
	}

}
