package sakila;

// Generated 07-mar-2017 10:05:25 by Hibernate Tools 3.4.0.CR1

/**
 * SalesByStore generated by hbm2java
 */
public class SalesByStore implements java.io.Serializable {

	private SalesByStoreId id;

	public SalesByStore() {
	}

	public SalesByStore(SalesByStoreId id) {
		this.id = id;
	}

	public SalesByStoreId getId() {
		return this.id;
	}

	public void setId(SalesByStoreId id) {
		this.id = id;
	}

}
